version: '3.6'
services:
  sticker-convert:
    # image: sticker-convert # Uncomment for building locally

    # Uncomment for building locally
    # build:
    #   context: .
    #   target: min-cli # Choices: min-gui, min-cli, full

    # Choose one of the following images, or comment out all if building locally
    image: laggykiller/sticker-convert:latest
    # image: laggykiller/sticker-convert:latest-min-cli
    # image: laggykiller/sticker-convert:latest-min-gui

    volumes:
      - ./stickers_input:/home/app/stickers_input
      - ./stickers_output:/home/app/stickers_output
      # - ./creds.json:/home/app/.config/sticker-convert/creds.json
      - /dev/shm:/dev/shm

    ports:
      - 5800:5800 # Port for Web UI
      # - 5900:5900 # Optional for VNC

    dns:
      - 1.1.1.1 # Or else download/upload to telegram fails in Docker

    # Your command here if you are using CLI
    # If you are launching GUI, do not comment out!
    # command: /usr/bin/python3 /app/sticker-convert.py --help